name: "Build ArduPlane"
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
    - run: nix-build
    # Newer versions don't support symlinks to directories
    # https://github.com/actions/upload-artifact/issues/92
    - uses: actions/upload-artifact@v1
      with:
        name: arduplane
        path: result
